### ISSUE TITLE
Build failed on create-react-app@1 because the published package is not ES5 compliant

### ISSUE THREAD

**Issue by compulim** [sindresorhus/p-defer#1]
When I am importing `p-defer` in `create-react-app@1` (with `react-scripts@1.1.4`), then run `npm run build`. I got the following error "Failed to minify the code from this file: p-defer/index.js:2".

The primary reason is because `index.js` is not ES5-compliant (use of arrow functions). If I modify two "arrow functions" into traditional one, it will pass `create-react-app` build.

```js
'use strict';
module.exports = function () {
	const ret = {};

	ret.promise = new Promise(function (resolve, reject) {
		ret.resolve = resolve;
		ret.reject = reject;
	});

	return ret;
};
```

On the other side, `create-react-app@2` changed the behavior and it will start building ES6+ files under `/node_modules/`. So it do not repro in `create-react-app@2`. But unfortunately, `create-react-app@2` was just released in October 1st 2018. I bet there are lots of projects still running under `create-react-app@1` and will keep it that way for another 1-2 years.

I am unsure if `p-defer` should be ES5 or ES6 compliant by default. NPM don't have a strict guideline. So I will leave it open for the contributors to decide how to resolve this issue.

Error from `npm run build` of `react-scripts`:

```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/p-defer/index.js:2

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playground@0.0.0-0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the playground@0.0.0-0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by sindresorhus** [comment]
I'm not going to change how I do modules just because of CRA v1. Now that CRA v2 is out, this is a non-issue, so closing this.
